### PR TITLE
Use `org.scalacheck.rng.Seed` instead of `Long` in CheckConfig

### LINKED ISSUE #632: CheckConfig should accept `org.scalacheck.rng.Seed` instead of `Long`
When a test fails it reports a base64 encoded `Seed`, from which we can attempt to construct it back with `org.scalacheck.rng.Seed#fromBase64`, but `CheckConfig` accepts `Long`.

### PR DESCRIPTION
**Pull request by dabd**
Closes https://github.com/disneystreaming/weaver-test/issues/632.

### CODE REVIEW

**Comment by Baccata** [comment]
that change is breaking source/binary compatibility. Instead, you could : 

1. create an alternative constructor for this case-class 
2. create a smart-setter / smart-getter `def withSeed` and `def seed`

**Comment by dabd** [comment]
> that change is breaking source/binary compatibility. Instead, you could :
> 
> 1. create an alternative constructor for this case-class
> 2. create a smart-setter / smart-getter `def withSeed` and `def seed`

For 1. you would need a way to go from `Seed` to `Long` and I don't see any obvious way to do that?

```scala
  def apply(
      minimumSuccessful: Int,
      maximumDiscardRatio: Int,
      maximumGeneratorSize: Int,
      perPropertyParallelism: Int,
      initialSeed: Option[Seed]): CheckConfig = 
    CheckConfig(minimumSuccessful,
                maximumDiscardRatio,
                maximumGeneratorSize,
                perPropertyParallelism,
                initialSeed.map(toLong))
  
  def toLong(s: Seed): Long = ???
```

**Comment by Baccata** [comment]
Errrgh, I see, the long value gets lost. This is annoying. Right, this will be a binary incompatible change, so let's not rush it, as we should switch from `case class` to normal class + builder pattern for the config. See [this](https://docs.scala-lang.org/overviews/core/binary-compatibility-for-library-authors.html#changing-a-case-class-definition-in-a-backwards-compatible-manner). 

NB, in case you didn't notice : you've PR'd against your own fork.

**Comment by dabd** [comment]
> 



> Errrgh, I see, the long value gets lost. This is annoying. Right, this will be a binary incompatible change, so let's not rush it, as we should switch from `case class` to normal class + builder pattern for the config. See [this](https://docs.scala-lang.org/overviews/core/binary-compatibility-for-library-authors.html#changing-a-case-class-definition-in-a-backwards-compatible-manner).

The example in the link still shows a `case class` but with a private constructor.  Are you going to use a normal class instead?  

> 
> NB, in case you didn't notice : you've PR'd against your own fork.

I wanted to stack this PR on top of the one you merged today and ended up in this situation.

**Comment by dabd** [comment]
Drafting it here instead https://github.com/disneystreaming/weaver-test/pull/633

**Pull request closed without merging**
